<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INC00752" name="com.incture.proj.testNg.TestNG" tests="3" failures="0" timestamp="28 Nov 2017 07:07:30 GMT" time="204.229" errors="1">
  <testcase name="main" time="37.591" classname="com.incture.proj.testNg.TestNG">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.incture.utility.CalenderController.selectDate(CalenderController.java:31)
	at com.incture.proj.appModules.EnterNewRow.enterNewRow(EnterNewRow.java:20)
	at com.incture.proj.appModules.Create_NewRow.TestCase(Create_NewRow.java:47)
	at com.incture.proj.appModules.Create_NewRow.test1(Create_NewRow.java:27)
	at com.incture.proj.testNg.TestNG.main(TestNG.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- main -->
  <testcase name="main" time="84.003" classname="com.incture.proj.testNg.TestNG"/>
  <testcase name="main" time="82.635" classname="com.incture.proj.testNg.TestNG"/>
</testsuite> <!-- com.incture.proj.testNg.TestNG -->
